[keyboard]
name = "Ergohaven Trackball Mini v3.1"
product_name = "Trackball Mini"
vendor_id = 0xE126
product_id = 0x00C2
manufacturer = "Ergohaven"
chip = "nrf52840"

[host]
vial_enabled = true
unlock_keys = [[0, 0], [0, 1]]

[event]
action.channel_size = 16
action.subs = 2
keyboard.subs = 4

[layout]
rows = 2
cols = 2
matrix_map = """
(0,0) (0,1)
(1,0) (1,1)
"""
layers = 16
no_action_layer_start = 5

[[layer]]
name = "Mouse"
keys = """
MouseBtn1  User14
User0      User5
"""

[[layer]]
name = "Scroll"
keys = """
_  _
_  _
"""

[[layer]]
name = "Sniper"
keys = """
_  _
_  _
"""

[[layer]]
name = "Adjust"
keys = """
User7   User8
User10  User11
"""

[ble]
enabled = true

[matrix]
matrix_type = "direct_pin"
direct_pins = [
    ["P0_28", "P0_03"],
    ["P0_01", "P0_00"]
]

[[input_device.pmw3610]]
name = "trackball0"
spi.instance = "bitbang0"
spi.sck = "P0_08"
spi.mosi = "P0_17"
spi.miso = "P0_17"
spi.cs = "P0_13"
motion = "P0_15"
cpi = 1000
swap_xy = true
invert_x = false
invert_y = false

[storage]
start_addr = 0xCC000
num_sectors = 32
clear_storage = false

[rmk]
ble_reconnect_timeout_seconds = 60
ble_pairing_timeout_seconds = 60
combo_max_num = 32
combo_max_length = 4
fork_max_num = 8
morse_max_num = 32
max_patterns_per_key = 8
macro_space_size = 2048
ble_profiles_num = 5
protocol_max_bulk_size = 8
protocol_macro_chunk_size = 64

[workspace]
members = ["."]
